// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// // const instrumentSans = Instrument_Sans({
// //   variable: "--font-instrument-sans",
// //   display: "swap",
// //   preload: true,
// //   style: ["normal", "italic"],
// //   subsets: ["latin"],
// // });
// import { Instrument_Sans } from "next/font/google";
// const instrumentSans = Instrument_Sans({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-instrument-sans",
// });

// // const instrumentSerif = Instrument_Sans({
// //   variable: "--font-instrument-serif",
// //   display: "swap",
// //   preload: true,
// // });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "My Portofolio",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistMono.variable} ${geistSans.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import type { Metadata } from "next";
import { Instrument_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-instrument-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${geistMono.variable}`}
    >
      <body className="antialiased font-sans">{children}</body>
    </html>
  );
}
